# ---------------------------------------------------------------------------- #
#                                   Variables                                  #
# ---------------------------------------------------------------------------- #
include Makefile.cfg

# ----------------------------------- Tools ---------------------------------- #
MKDIR				:= mkdir
RM					:= rm
ECHO				:= /usr/bin/echo

CC					:= gcc
AR					:= ar rcs

CWARN				:= all extra error
CWARN				:= $(CWARN:%=-W%)

CFLAGS				:= -fPIC -MMD $(CWARN) -std=c17 -pthread \
	-fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc \
	-fno-strict-aliasing -fvisibility=hidden \
	$(if $(OPTIMIZE),-O2,) \
	$(if $(DEBUG),-g3 -O0 -DFTM_DEBUG,) \
	$(CMOREFLAGS)

LD					:= gcc
LDFLAGS				:= -shared -pthread $(LDMOREFLAGS)
LD_LIBS				:=

AS					:= as
ASFLAGS				:= $(if $(filter $(ARCH),64),,--32)

# ---------------------------------- Release --------------------------------- #
ifeq ($(HOSTTYPE),)
	HOSTTYPE := $(shell uname -m)_$(shell uname -s)
endif
NAME				:= libft_malloc_$(HOSTTYPE).so
LINK				:= libft_malloc.so
NAME_PATH			:= $(OUTDIR)/$(NAME)
LINK_PATH			:= $(OUTDIR)/$(LINK)

# ------------------------------- Dependencies ------------------------------- #
THIRDPARTY			:= thirdparty
LIBS				:= libft

LIBS_MAKE_RULE		:=
LIBS_CLEAN_RULE		:=
LIBS_FCLEAN_RULE	:=

define get-lib-info
include $(THIRDPARTY)/$1.dep
LD_LIBS += $$(LIBA_$1:lib%.a=-l%) $$(DEP_LD_LIBS_$1)
CFLAGS  += -I$(THIRDPARTY)/$$(INCDIR_$1)
LDFLAGS += -L$(THIRDPARTY)/$$(LIBDIR_$1)
LIBS_MAKE_RULE   += MAKE_RULE_$1
LIBS_CLEAN_RULE  += CLEAN_RULE_$1
LIBS_FCLEAN_RULE += FCLEAN_RULE_$1
endef

$(foreach lib, $(LIBS),$(eval $(call get-lib-info,$(lib))))

# ---------------------------------- Sources --------------------------------- #
SRCDIR				:= src
INCDIR				:= include
ARCH_DIR			:= $(if $(filter $(ARCH),64),x86_64,i386)

CFLAGS				+= -I$(INCDIR)

SRCS				:= $(wildcard $(SRCDIR)/*.c) \
					$(wildcard $(SRCDIR)/core/*.c) \
					$(wildcard $(SRCDIR)/port/*.c)
OBJS				:= $(SRCS:$(SRCDIR)/%.c=$(OBJDIR)/%.c.o)
DEPS				:= $(OBJS:%.c.o=%.c.d)

# ----------------------------- Current arch asm ----------------------------- #
SRCS_ASM			:= $(wildcard $(SRCDIR)/arch/$(ARCH_DIR)/*.S)
OBJS				+= $(SRCS_ASM:$(SRCDIR)/%.S=$(OBJDIR)/%.S.o)